# Generated by Django 3.2.18 on 2023-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_club_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.CharField(default='website\\static\\sc_nophoto.webp', max_length=200),
        ),
    ]
