# Generated by Django 3.2.18 on 2023-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230320_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
