# Generated by Django 3.2.18 on 2023-03-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_club_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='students',
            new_name='users_id',
        ),
    ]
