# Generated by Django 3.2.18 on 2023-04-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_students_club_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(max_length=250, upload_to='images/'),
        ),
    ]
